name: image_editor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  photofilters: ^3.0.1
  image_picker: ^0.8.5+3
  saver_gallery: ^1.0.1
  permission_handler: ^9.2.0
  flutter_easyloading: ^3.0.5
  applovin_max: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

